PR
umitkucuk/vue-playground pull request #5
Opened 2018-11-13 19:31 UTC by 2ez4salt

2018-11-13 19:35 UTC, buremba requested changes
`.idea` klasoru senin localinde olmasi gereken bir dizin, dolayisiyla bunu git'e gondermemen gerekiyor. .gitignore'a ekleyip bu PR'dan silebilirsen iyi olur.

2018-11-13 19:35 UTC, buremba commented on components/Header/index.vue
> +    <el-menu-item index="/SaltPage">
Eger convention kebab case ise senin de o sekilde devam etmen gerekiyor. Bu projede @umitkucuk kebab case kullanmis URL'ler icin `app-sections` gibi, senin de `SaltPage` degil `salt-page` seklinde yapman gerekiyor dolayisiyla.

2018-11-13 19:35 UTC, buremba commented on pages/SaltPage.vue
> +    arr = [];
Bu tarz degiskenlerin classin en ustunde olmasi gerekiyor genellikle, data() uzerine tasir misin `arr` degiskenini?

2018-11-13 19:36 UTC, buremba commented
Bu yukardaki review'in disinda PR ismi ve commit isimlerinin de anlasilabilir olmasi gerekiyor, burda guzek bir aciklama var konuyla ilgili: https://chris.beams.io/posts/git-commit/
Bu PR'in ismini guncelleyip bundan sonraki commit'lerde isme dikkat edebilir misin?

2018-11-13 20:12 UTC, buremba requested changes
.idea klasorunde hala dosyalar gozukuyor, onlari da bu PR'dan silmen gerekiyor.

2018-11-13 20:38 UTC, 2ez4salt commented
sildim abi

2018-11-13 20:47 UTC, buremba approved these changes

2018-11-13 21:42 UTC, umitkucuk commented
@2ez4salt; `input` değişkenini aynı `arr` değişkeni gibi instance'da tanımlaman gerekiyor. Ayrıca input boş olduğunda **Click Me** butonu tıklanamaz(disabled) olsun. 👌

2018-11-15 15:46 UTC, 2ez4salt commented
uğraştım ama yapamadım :( fonksiyonu yazdım state change yapamadım toggle butonuna tıklayınca inputun içine göre buton stateini değiştirebiliyorum fakat otomatik yapamadım

2023-10-30 11:53 UTC, closed without merging